services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # UI de administraci√≥n
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - notification_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16-alpine
    container_name: postgres_notifications
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: parkin
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: db_notification
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - notification_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parkin -d db_notification"]
      interval: 10s
      timeout: 5s
      retries: 5

  ms-notifications:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-notifications
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_notification
      SPRING_DATASOURCE_USERNAME: parkin
      SPRING_DATASOURCE_PASSWORD: qwerty123
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JAVA_OPTS: "-Xms256m -Xmx512m"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - notification_network
    restart: unless-stopped

networks:
  notification_network:
    driver: bridge

volumes:
  pgdata:
