spring:
  datasource:
    url: jdbc:postgresql://fleet-db:5432/fleet_db
    username: fleet_user
    password: fleet_password

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
